try {
  let number = 20;
  number();
} catch (exception) {
  console.log('예외를 처리하겟슴!')
}